### ISSUE TITLE
Wireguard support?

### ISSUE THREAD

**Issue by zilexa** [microbug/docker-cryptostorm-client#7]
Now that Cryptostorm has Wireguard support, are you considering adding support in this container?
(sorry for the spam, I just cancelled my NordVPN subscription and your image is a big plus to switch to Cryptostorm :)

**Comment by microbug** [comment]
I'm afraid I'm not using this container anymore so I'm not looking to do much work on it. But I'm happy to accept a PR if you'd like to implement Wireguard!

**Comment by SkyperTHC** [comment]
I wrote one: https://hub.docker.com/r/hackerschoice/cryptostorm
